- hosts: localhost
  connection: local
  vars:
    ami: ami-09de4a4c670389e4b
    sec_group: sg-0a7aa666d5b51f2a8
    region: eu-central-1
    subnet: subnet-7853cf03
    server: my_new_server
    ssh_key: ansible-eu-central
    ami_user: ec2-user
    ami_os: RHEL
  roles:
    - create-ec2
